name: pecoff
version: '0.11'
synopsis: Parser for PE/COFF format.
description: Parser for PE/COFF format.
category: Data
author: Erik Charlebois
maintainer: Erik Charlebois <erikcharlebois@gmail.com>
copyright: Erik Charlebois
license: BSD3
dependencies:
- base >=4 && <5
- bytestring
- containers
- binary
library:
  source-dirs: src
tests:
  test:
    source-dirs: tests
    main: Test.hs
    dependencies:
    - HUnit
    - pecoff
stability: unstable
