name: pecoff-fork
version: '0.2'
synopsis: Parser for PE/COFF format.
description: Parser for PE/COFF format.
category: Data
author: Erik Charlebois, Michał Wawrzyniec Urbańczyk
maintainer: Michał Wawrzyniec Urbańczyk <mwu-tow@gazeta.pl>
copyright: Erik Charlebois, Michał Wawrzyniec Urbańczyk
license: BSD3
dependencies:
- base
- bytestring
- containers
- binary
- time
- transformers
ghc-options: -Werror -Wmissing-fields
library:
  source-dirs: src
tests:
  test:
    source-dirs: tests
    main: Test.hs
    dependencies:
    - HUnit
    - pecoff
stability: unstable

default-extensions:
  AllowAmbiguousTypes
  LambdaCase
  DuplicateRecordFields 
  FlexibleContexts
  FlexibleInstances
  InstanceSigs
  OverloadedStrings
  RankNTypes
  RecordWildCards
  ScopedTypeVariables
  TypeApplications
  TypeFamilies
  UndecidableInstances